import React, { useState } from 'react';
import { View, StyleSheet, Text, TextInput } from 'react-native';

import ElementCard from './Elementos.js/Elementos';

const App = () => {
  const [elementInfo, setElementInfo] = useState(null);

  const elements = {
  1: { symbol: 'H', name: 'Hidrogênio', atomicNumber: 1, atomicMass: 1 },
  9: { symbol: 'He', name: 'Hélio', atomicNumber: 2, atomicMass: 4 },
  2: { symbol: 'Li', name: 'Lítio', atomicNumber: 3, atomicMass: 7 },
  3: { symbol: 'Be', name: 'Berílio', atomicNumber: 4, atomicMass: 9 },
  4: { symbol: 'B', name: 'Boro', atomicNumber: 5, atomicMass: 11 },
  5: { symbol: 'C', name: 'Carbono', atomicNumber: 6, atomicMass: 12 },
  6: { symbol: 'N', name: 'Nitrogênio', atomicNumber: 7, atomicMass: 14 },
  7: { symbol: 'O', name: 'Oxigênio', atomicNumber: 8, atomicMass: 16 },
  8: { symbol: 'F', name: 'Flúor', atomicNumber: 9, atomicMass: 19 },
  R: { symbol: 'Si', name: 'Silício', atomicNumber: 14, atomicMass: 28 },
  Q: { symbol: 'Na', name: 'Sódio', atomicNumber: 11, atomicMass: 23 },
  W: { symbol: 'Mg', name: 'Magnésio', atomicNumber: 12, atomicMass: 24 },
  E: { symbol: 'Al', name: 'Alumínio', atomicNumber: 13, atomicMass: 27 },
  Z: { symbol: 'Sr', name: 'Estrôncio', atomicNumber: 38, atomicMass: 88 },
  T: { symbol: 'P', name: 'Fósforo', atomicNumber: 15, atomicMass: 31 },
  Y: { symbol: 'S', name: 'Enxofre', atomicNumber: 16, atomicMass: 32 },
  U: { symbol: 'Cl', name: 'Cloro', atomicNumber: 17, atomicMass: 35 },
  I: { symbol: 'Ar', name: 'Argônio', atomicNumber: 18, atomicMass: 40 },
  A: { symbol: 'K', name: 'Potássio', atomicNumber: 19, atomicMass: 39 },
  D: { symbol: 'Ga', name: 'Gálio', atomicNumber: 31, atomicMass: 70 },
  V: { symbol: 'Sc', name: 'Escândio', atomicNumber: 21, atomicMass: 45 },
  0: { symbol: 'Ti', name: 'Titânio', atomicNumber: 22, atomicMass: 48 },
  O: { symbol: 'Fe', name: 'Ferro', atomicNumber: 26, atomicMass: 56 },
  P: { symbol: 'Co', name: 'Cobalto', atomicNumber: 27, atomicMass: 59 },
  S: { symbol: 'Ca', name: 'Cálcio', atomicNumber: 20, atomicMass: 40 },
  F: { symbol: 'As', name: 'Arsênio', atomicNumber: 33, atomicMass: 75 },
  G: { symbol: 'Br', name: 'Bromo', atomicNumber: 35, atomicMass: 80 },
  H: { symbol: 'I', name: 'Iodo', atomicNumber: 53, atomicMass: 127 },
  J: { symbol: 'Kr', name: 'Criptônio', atomicNumber: 36, atomicMass: 84 },
  K: { symbol: 'Xe', name: 'Xenônio', atomicNumber: 54, atomicMass: 131 },
  L: { symbol: 'W', name: 'Tungstênio', atomicNumber: 74, atomicMass: 184 },
  X: { symbol: 'Cs', name: 'Césio', atomicNumber: 55, atomicMass: 133 },
  C: { symbol: 'Ba', name: 'Bário', atomicNumber: 56, atomicMass: 137 },
  V: { symbol: 'Sn', name: 'Estanho', atomicNumber: 50, atomicMass: 119 },
  B: { symbol: 'Pb', name: 'Chumbo', atomicNumber: 82, atomicMass: 207 },
  N: { symbol: 'Po', name: 'Polônio', atomicNumber: 84, atomicMass: 209 },
  M: { symbol: 'Fr', name: 'Frâncio', atomicNumber: 87, atomicMass: 223 },
  Ç: { symbol: 'Zn', name: 'Zinco', atomicNumber: 30, atomicMass: 65 },
  '[': { symbol: 'Cu', name: 'Cobre', atomicNumber: 29, atomicMass: 63 },
  ']': { symbol: 'Ag', name: 'Prata', atomicNumber: 47, atomicMass: 108 },
  '.': { symbol: 'Pt', name: 'Platina', atomicNumber: 78, atomicMass: 195 },
  '-': { symbol: 'Cr', name: 'Crômio', atomicNumber: 24, atomicMass: 52 },
  '=': { symbol: 'Mn', name: 'Manganês', atomicNumber: 25, atomicMass: 55 },
  '´': { symbol: 'Ni', name: 'Níquel', atomicNumber: 28, atomicMass: 59 },
  '~': { symbol: 'Pd', name: 'Paládio', atomicNumber: 46, atomicMass: 108 },
  ',': { symbol: 'Ra', name: 'Rádio', atomicNumber: 88, atomicMass: 226 },
  ';': { symbol: 'Au', name: 'Ouro', atomicNumber: 79, atomicMass: 197 },
  '/': { symbol: 'Hg', name: 'Mercúrio', atomicNumber: 80, atomicMass: 200 }

  };

  const combinations = {
    17: { symbol: 'H2O', name: 'Água', reaction: 'H2 + 1/2 O2 -> H2O' },
    71: { symbol: 'H2O', name: 'Água', reaction: 'H2 + 1/2 O2 -> H2O' },
    15: { symbol: 'CH4', name: 'Metano', reaction: 'CO2 + 2 H2O -> CH4 + 2 O2' },
    51: { symbol: 'CH4', name: 'Metano', reaction: 'CO2 + 2 H2O -> CH4 + 2 O2' },
    27: { symbol: 'LiO2', name: 'Óxido de lítio', reaction: '2 Li + 1/2 O2 -> LiO2' },
    72: { symbol: 'LiO2', name: 'Óxido de lítio', reaction: '2 Li + 1/2 O2 -> LiO2' },
    172: { symbol: 'LiOH', name: 'Hidróxido de lítio', reaction: '2 Li + 2 H2O -> 2 LiOH + H2' },
    127: { symbol: 'LiOH', name: 'Hidróxido de lítio', reaction: '2 Li + 2 H2O -> 2 LiOH + H2' },
    721: { symbol: 'LiOH', name: 'Hidróxido de lítio', reaction: '2 Li + 2 H2O -> 2 LiOH + H2' },
    712: { symbol: 'LiOH', name: 'Hidróxido de lítio', reaction: '2 Li + 2 H2O -> 2 LiOH + H2' },
    271: { symbol: 'LiOH', name: 'Hidróxido de lítio', reaction: '2 Li + 2 H2O -> 2 LiOH + H2' },
    217: { symbol: 'LiOH', name: 'Hidróxido de lítio', reaction: '2 Li + 2 H2O -> 2 LiOH + H2' },
    28: { symbol: 'LiF', name: 'Fluoreto de lítio', reaction: 'LiOH + HF -> LiF + H2O' },
    82: { symbol: 'LiF', name: 'Fluoreto de lítio', reaction: 'LiOH + HF -> LiF + H2O' },
    '2U': { symbol: 'LiCl', name: 'Cloreto de lítio', reaction: 'LiOH + HCl -> LiCl + H2O' },
    'U2': { symbol: 'LiCl', name: 'Cloreto de lítio', reaction: 'LiOH + HCl -> LiCl + H2O' },
    '2G': { symbol: 'LiBr', name: 'Brometo de lítio', reaction: 'LiOH + HBr -> LiBr + H2O' },
    'G2': { symbol: 'LiBr', name: 'Brometo de lítio', reaction: 'LiOH + HBr -> LiBr + H2O' },
    26: { symbol: 'Li3N', name: 'Nitreto de lítio', reaction: '3 Li + 1/2 N2 -> Li3N' },
    62: { symbol: 'Li3N', name: 'Nitreto de lítio', reaction: '3 Li + 1/2 N2 -> Li3N' },
    37: { symbol: 'BeO', name: 'Óxido de berílio', reaction: 'Be + 1/2 O2 -> BeO' },
    73: { symbol: 'BeO', name: 'Óxido de berílio', reaction: 'Be + 1/2 O2 -> BeO' },
    371: { symbol: 'Be(OH)2', name: 'Hidróxido de berílio', reaction: 'BeH2 + 2 H2O -> Be(OH)2 + 2 H2' },
    317: { symbol: 'Be(OH)2', name: 'Hidróxido de berílio', reaction: 'BeH2 + 2 H2O -> Be(OH)2 + 2 H2' },
    713: { symbol: 'Be(OH)2', name: 'Hidróxido de berílio', reaction: 'BeH2 + 2 H2O -> Be(OH)2 + 2 H2' },
    731: { symbol: 'Be(OH)2', name: 'Hidróxido de berílio', reaction: 'BeH2 + 2 H2O -> Be(OH)2 + 2 H2' },
    137: { symbol: 'Be(OH)2', name: 'Hidróxido de berílio', reaction: 'BeH2 + 2 H2O -> Be(OH)2 + 2 H2' },
    173: { symbol: 'Be(OH)2', name: 'Hidróxido de berílio', reaction: 'BeH2 + 2 H2O -> Be(OH)2 + 2 H2' },
    38: { symbol: 'BeF2', name: 'Fluoreto de berílio', reaction: '2 HF + Be(OH)2 -> 2 H2O + MgF2' },
    83: { symbol: 'BeF2', name: 'Fluoreto de berílio', reaction: '2 HF + Be(OH)2 -> 2 H2O + MgF2' },
    '3U': { symbol: 'BeCl2', name: 'Cloreto de berílio', reaction: '2 HCl + Be(OH)2 -> 2 H2O + MgCl2' },
    'U3': { symbol: 'BeCl2', name: 'Cloreto de berílio', reaction: '2 HCl + Be(OH)2 -> 2 H2O + MgCl2' },
    48: { symbol: 'BF3', name: 'Trifluoreto de boro', reaction: '2 B + 6 HF -> 2 BF3 + 3 H2' },
    84: { symbol: 'BF3', name: 'Trifluoreto de boro', reaction: '2 B + 6 HF -> 2 BF3 + 3 H2' },
    '4U': { symbol: 'BCl3', name: 'Tricloreto de boro', reaction: '2 B + 6 HCl -> 2 BCl3 + 3 H2' },
    'U4': { symbol: 'BCl3', name: 'Tricloreto de boro', reaction: '2 B + 6 HCl -> 2 BCl3 + 3 H2' },
    '4G': { symbol: 'BBr3', name: 'Tribrometo de boro', reaction: '2 B + 6 HBr -> 2 BBr3 + 3 H2' },
    'G4': { symbol: 'BBr3', name: 'Tribrometo de boro', reaction: '2 B + 6 HBr -> 2 BBr3 + 3 H2' },
    46: { symbol: 'BN', name: 'Nitreto de boro', reaction: 'B2O3 + N2 -> 2 BN + 1/2 O2'  },
    64: { symbol: 'BN', name: 'Nitreto de boro', reaction: 'B2O3 + N2 -> 2 BN + 1/2 O2' },
    41: { symbol: 'BH3', name: 'borano', reaction: 'B + 3/2 H2 -> BH3' },
    14: { symbol: 'BH3', name: 'borano', reaction: 'B + 3/2 H2 -> BH3' },
    47: { symbol: 'B2O3', name: 'Óxido de boro', reaction: '2 H3BO3 -> B2O3 + 3 H2O' },
    74: { symbol: 'B2O3', name: 'Óxido de boro', reaction: '2 H3BO3 -> B2O3 + 3 H2O' },
    741: { symbol: 'H3BO3', name: 'Ácido bórico', reaction: '3 H2O + Na3BO4 -> H3BO3 + 3 NaOH' },
    714: { symbol: 'H3BO3', name: 'Ácido bórico', reaction: '3 H2O + Na3BO4 -> H3BO3 + 3 NaOH' },
    471: { symbol: 'H3BO3', name: 'Ácido bórico', reaction: '3 H2O + Na3BO4 -> H3BO3 + 3 NaOH' },
    417: { symbol: 'H3BO3', name: 'Ácido bórico', reaction: '3 H2O + Na3BO4 -> H3BO3 + 3 NaOH' },
    147: { symbol: 'H3BO3', name: 'Ácido bórico', reaction: '3 H2O + Na3BO4 -> H3BO3 + 3 NaOH' },
    174: { symbol: 'H3BO3', name: 'Ácido bórico', reaction: '3 H2O + Na3BO4 -> H3BO3 + 3 NaOH' },
    'Q14': { symbol: 'NaBH4', name: 'Boro-hidreto de sódio', reaction: 'B(OCH3)3 + 4 NaH -> NaBH4 + 3 NaOCH3' },
    'Q41': { symbol: 'NaBH4', name: 'Boro-hidreto de sódio', reaction: 'B(OCH3)3 + 4 NaH -> NaBH4 + 3 NaOCH3' },
    '4Q1': { symbol: 'NaBH4', name: 'Boro-hidreto de sódio', reaction: 'B(OCH3)3 + 4 NaH -> NaBH4 + 3 NaOCH3' },
    '41Q': { symbol: 'NaBH4', name: 'Boro-hidreto de sódio', reaction: 'B(OCH3)3 + 4 NaH -> NaBH4 + 3 NaOCH3' },
    '1Q4': { symbol: 'NaBH4', name: 'Boro-hidreto de sódio', reaction: 'B(OCH3)3 + 4 NaH -> NaBH4 + 3 NaOCH3' },
    '14Q': { symbol: 'NaBH4', name: 'Boro-hidreto de sódio', reaction: 'B(OCH3)3 + 4 NaH -> NaBH4 + 3 NaOCH3' },
    57: { symbol: 'CO2', name: 'Dióxido de carbono', reaction: 'CH4 + 2 O2 -> CO2 + 2H2O' },
    75: { symbol: 'CO2', name: 'Dióxido de carbono', reaction: 'CH4 + 2 O2 -> CO2 + 2H2O' },
    '5U': { symbol: 'CCl4', name: 'Tetracloreto de carbono', reaction: 'CH4 + 4 Cl2 -> CCl4 + 4 HCl' }, 
    'U5': { symbol: 'CCl4', name: 'Tetracloreto de carbono', reaction: 'CH4 + 4 Cl2 -> CCl4 + 4 HCl' }, 
    '5G': { symbol: 'CBr4', name: 'Tetrabrometo de carbono', reaction: 'CH4 + 4 Cl2 -> CCl4 + 4 HCl' },
    'G5': { symbol: 'CBr4', name: 'Tetrabrometo de carbono', reaction: 'CH4 + 4 Cl2 -> CCl4 + 4 HCl' },
    '58': { symbol: 'CF4', name: 'Tetrafluoreto de carbono', reaction: 'CH4 + 4 Cl2 -> CCl4 + 4 HCl' },
    '85': { symbol: 'CF4', name: 'Tetrafluoreto de carbono', reaction: 'CH4 + 4 Cl2 -> CCl4 + 4 HCl' },
    61: { symbol: 'NH3', name: 'Amônia', reaction: 'N2 + 3 H2 -> 2 NH3' },
    16: { symbol: 'NH3', name: 'Amônia', reaction: 'N2 + 3 H2 -> 2 NH3' },
    67: { symbol: 'NO2', name: 'Dióxido de nitrogênio', reaction: '2 NO + O2 -> 2 NO2' },
    76: { symbol: 'NO2', name: 'Dióxido de nitrogênio', reaction: '2 NO + O2 -> 2 NO2' },
    671: { symbol: 'HNO3', name: 'Ácido nítrico', reaction: '3 NO2 + H2O -> 2 HNO3 + NO' },
    617: { symbol: 'HNO3', name: 'Ácido nítrico', reaction: '3 NO2 + H2O -> 2 HNO3 + NO' },
    761: { symbol: 'HNO3', name: 'Ácido nítrico', reaction: '3 NO2 + H2O -> 2 HNO3 + NO' },
    716: { symbol: 'HNO3', name: 'Ácido nítrico', reaction: '3 NO2 + H2O -> 2 HNO3 + NO' },
    167: { symbol: 'HNO3', name: 'Ácido nítrico', reaction: '3 NO2 + H2O -> 2 HNO3 + NO' },
    176: { symbol: 'HNO3', name: 'Ácido nítrico', reaction: '3 NO2 + H2O -> 2 HNO3 + NO' },
    68: { symbol: 'NF3', name: 'Trifluoreto de nitrogênio', reaction: '3 F2 + N2 -> 2 NF3' },
    86: { symbol: 'NF3', name: 'Trifluoreto de nitrogênio', reaction: '3 F2 + N2 -> 2 NF3' },
    '6U': { symbol: 'NCl3', name: 'Tricloreto de nitrogênio', reaction: '3 Cl2 + N2 -> 2 NCl3' },
    'U6': { symbol: 'NCl3', name: 'Tricloreto de nitrogênio', reaction: '3 Cl2 + N2 -> 2 NCl3' },
    '6G': { symbol: 'NBr3', name: 'Tribrometo de nitrogênio', reaction: '3 Br2 + N2 -> 2 NBr3' },
    'G6': { symbol: 'NBr3', name: 'Tribrometo de nitrogênio', reaction: '3 Br2 + N2 -> 2 NBr3' },
    '6H': { symbol: 'NI3', name: 'Triiodeto de nitrogênio', reaction: '3 I2 + N2 -> 2 NI3' },
    'H6': { symbol: 'NI3', name: 'Triiodeto de nitrogênio', reaction: '3 I2 + N2 -> 2 NI3' },
    156: { symbol: 'HCN', name: 'Cianeto de hidrogênio', reaction: '2 CH4 + 2 NH3 + 3 O2 -> 2 HCN + 6 H2O' },
    165: { symbol: 'HCN', name: 'Cianeto de hidrogênio', reaction: '2 CH4 + 2 NH3 + 3 O2 -> 2 HCN + 6 H2O' },
    651: { symbol: 'HCN', name: 'Cianeto de hidrogênio', reaction: '2 CH4 + 2 NH3 + 3 O2 -> 2 HCN + 6 H2O' },
    615: { symbol: 'HCN', name: 'Cianeto de hidrogênio', reaction: '2 CH4 + 2 NH3 + 3 O2 -> 2 HCN + 6 H2O' },
    561: { symbol: 'HCN', name: 'Cianeto de hidrogênio', reaction: '2 CH4 + 2 NH3 + 3 O2 -> 2 HCN + 6 H2O' },
    516: { symbol: 'HCN', name: 'Cianeto de hidrogênio', reaction: '2 CH4 + 2 NH3 + 3 O2 -> 2 HCN + 6 H2O' },
    '67A': { symbol: 'KNO3', name: 'Nitrato de potássio', reaction: 'HNO3 + KOH -> KNO3 + H2O' },
    '6A7': { symbol: 'KNO3', name: 'Nitrato de potássio', reaction: 'HNO3 + KOH -> KNO3 + H2O' },
    '76A': { symbol: 'KNO3', name: 'Nitrato de potássio', reaction: 'HNO3 + KOH -> KNO3 + H2O' },
    '7A6': { symbol: 'KNO3', name: 'Nitrato de potássio', reaction: 'HNO3 + KOH -> KNO3 + H2O' },
    'A76': { symbol: 'KNO3', name: 'Nitrato de potássio', reaction: 'HNO3 + KOH -> KNO3 + H2O' },
    'A67': { symbol: 'KNO3', name: 'Nitrato de potássio', reaction: 'HNO3 + KOH -> KNO3 + H2O' },
    618: { symbol: 'NH2F', name: 'Fluoramina', reaction: 'NH3 + HFO -> NH2F + H2O' },
    681: { symbol: 'NH2F', name: 'Fluoramina', reaction: 'NH3 + HFO -> NH2F + H2O' },
    861: { symbol: 'NH2F', name: 'Fluoramina', reaction: 'NH3 + HFO -> NH2F + H2O' },
    816: { symbol: 'NH2F', name: 'Fluoramina', reaction: 'NH3 + HFO -> NH2F + H2O' },
    168: { symbol: 'NH2F', name: 'Fluoramina', reaction: 'NH3 + HFO -> NH2F + H2O' },
    186: { symbol: 'NH2F', name: 'Fluoramina', reaction: 'NH3 + HFO -> NH2F + H2O' },
    '8Q': { symbol: 'NaF', name: 'Fluoreto de sódio', reaction: 'HF + NaCl -> NaF + HCl' },
    'Q8': { symbol: 'NaF', name: 'Fluoreto de sódio', reaction: 'HF + NaCl -> NaF + HCl' },
    '8S': { symbol: 'CaF2', name: 'Fluoreto de cálcio (fluorita)', reaction: 'CaO + 2 HF -> CaF2 + H2O' },
    'S8': { symbol: 'CaF2', name: 'Fluoreto de cálcio (fluorita)', reaction: 'CaO + 2 HF -> CaF2 + H2O' },
    '8QE': { symbol: 'Na3AlF6', name: 'Hexafluoraluminato de sódio (criolita)', reaction: '6 NaOH + Al2O3 + 12 HF -> 2 Na3AlF6 + 9 H2O' },
    '8EQ': { symbol: 'Na3AlF6', name: 'Hexafluoraluminato de sódio (criolita)', reaction: '6 NaOH + Al2O3 + 12 HF -> 2 Na3AlF6 + 9 H2O' },
    'QE8': { symbol: 'Na3AlF6', name: 'Hexafluoraluminato de sódio (criolita)', reaction: '6 NaOH + Al2O3 + 12 HF -> 2 Na3AlF6 + 9 H2O' },
    'Q8E': { symbol: 'Na3AlF6', name: 'Hexafluoraluminato de sódio (criolita)', reaction: '6 NaOH + Al2O3 + 12 HF -> 2 Na3AlF6 + 9 H2O' },
    'E8Q': { symbol: 'Na3AlF6', name: 'Hexafluoraluminato de sódio (criolita)', reaction: '6 NaOH + Al2O3 + 12 HF -> 2 Na3AlF6 + 9 H2O' },
    'EQ8': { symbol: 'Na3AlF6', name: 'Hexafluoraluminato de sódio (criolita)', reaction: '6 NaOH + Al2O3 + 12 HF -> 2 Na3AlF6 + 9 H2O' },
    '8Y': { symbol: 'SF6', name: 'Fluoreto de enxofre', reaction: '6 HF + SO2 -> SF6 + 3 H2 + O2' },
    'Y8': { symbol: 'SF6', name: 'Fluoreto de enxofre', reaction: '6 HF + SO2 -> SF6 + 3 H2 + O2' },
    81: { symbol: 'HF', name: 'Ácido fluorídrico', reaction: 'IF5 + 3 H2O -> HIO3 + 5 HF' },
    18: { symbol: 'HF', name: 'Ácido fluorídrico', reaction: 'IF5 + 3 H2O -> HIO3 + 5 HF' },
    '8H': { symbol: 'IF5', name: 'Pentafluoreto de iodo', reaction: 'I2 + 5 F2 -> 2 IF5' },
    'H8': { symbol: 'IF5', name: 'Pentafluoreto de iodo', reaction: 'I2 + 5 F2 -> 2 IF5' },
    'H,': { symbol: 'PtF6', name: 'Hexafluoreto de platina', reaction: 'Pt + 3 F2 -> PtF6' },
    ',H': { symbol: 'PtF6', name: 'Hexafluoreto de platina', reaction: 'Pt + 3 F2 -> PtF6' },
    'Q17': { symbol: 'NaOH', name: 'Hidróxido de sódio (soda cáustica)', reaction: '2 NaCl + 2 H2O -> 2 NaOH + Cl2 + H2' },
    'Q71': { symbol: 'NaOH', name: 'Hidróxido de sódio (soda cáustica)', reaction: '2 NaCl + 2 H2O -> 2 NaOH + Cl2 + H2' },
    '1Q7': { symbol: 'NaOH', name: 'Hidróxido de sódio (soda cáustica)', reaction: '2 NaCl + 2 H2O -> 2 NaOH + Cl2 + H2' },
    '17Q': { symbol: 'NaOH', name: 'Hidróxido de sódio (soda cáustica)', reaction: '2 NaCl + 2 H2O -> 2 NaOH + Cl2 + H2' },
    '7Q1': { symbol: 'NaOH', name: 'Hidróxido de sódio (soda cáustica)', reaction: '2 NaCl + 2 H2O -> 2 NaOH + Cl2 + H2' },
    '71Q': { symbol: 'NaOH', name: 'Hidróxido de sódio (soda cáustica)', reaction: '2 NaCl + 2 H2O -> 2 NaOH + Cl2 + H2' },
    'QU': { symbol: 'NaCl', name: 'Cloreto de sódio (sal de cozinha)', reaction: 'NaOH + HCl -> NaCl + H2O' },
    'UQ': { symbol: 'NaCl', name: 'Cloreto de sódio (sal de cozinha)', reaction: 'NaOH + HCl -> NaCl + H2O' },
    'UQ7': { symbol: 'NaClO', name: 'Hipoclorito de sódio (alvejante)', reaction: '2 NaOH + Cl2 -> NaCl + NaClO + H2O' },
    'U7Q': { symbol: 'NaClO', name: 'Hipoclorito de sódio (alvejante)', reaction: '2 NaOH + Cl2 -> NaCl + NaClO + H2O' },
    '7QU': { symbol: 'NaClO', name: 'Hipoclorito de sódio (alvejante)', reaction: '2 NaOH + Cl2 -> NaCl + NaClO + H2O' },
    '7UQ': { symbol: 'NaClO', name: 'Hipoclorito de sódio (alvejante)', reaction: '2 NaOH + Cl2 -> NaCl + NaClO + H2O' },
    'Q7U': { symbol: 'NaClO', name: 'Hipoclorito de sódio (alvejante)', reaction: '2 NaOH + Cl2 -> NaCl + NaClO + H2O' },
    'QU7': { symbol: 'NaClO', name: 'Hipoclorito de sódio (alvejante)', reaction: '2 NaOH + Cl2 -> NaCl + NaClO + H2O' },
    'Q57': { symbol: 'Na2CO3', name: 'Carbonato de sódio', reaction: 'Na2SO4 + CaCO3 + 2 C -> Na2CO3 + CaS + 2 CO2' },
    '5Q7': { symbol: 'Na2CO3', name: 'Carbonato de sódio', reaction: 'Na2SO4 + CaCO3 + 2 C -> Na2CO3 + CaS + 2 CO2' },
    '75Q': { symbol: 'Na2CO3', name: 'Carbonato de sódio', reaction: 'Na2SO4 + CaCO3 + 2 C -> Na2CO3 + CaS + 2 CO2' },
    'Q75': { symbol: 'Na2CO3', name: 'Carbonato de sódio', reaction: 'Na2SO4 + CaCO3 + 2 C -> Na2CO3 + CaS + 2 CO2' },
    '7Q5': { symbol: 'Na2CO3', name: 'Carbonato de sódio', reaction: 'Na2SO4 + CaCO3 + 2 C -> Na2CO3 + CaS + 2 CO2' },
    '57Q': { symbol: 'Na2CO3', name: 'Carbonato de sódio', reaction: 'Na2SO4 + CaCO3 + 2 C -> Na2CO3 + CaS + 2 CO2' },
    'Q74': { symbol: 'Na2B4O7', name: 'Bórax', reaction: '2 H3BO3 + 2 NaBO2 -> Na2B4O7 + 3 H2O' },
    'Q47': { symbol: 'Na2B4O7', name: 'Bórax', reaction: '2 H3BO3 + 2 NaBO2 -> Na2B4O7 + 3 H2O' },
    '7Q4': { symbol: 'Na2B4O7', name: 'Bórax', reaction: '2 H3BO3 + 2 NaBO2 -> Na2B4O7 + 3 H2O' },
    '74Q': { symbol: 'Na2B4O7', name: 'Bórax', reaction: '2 H3BO3 + 2 NaBO2 -> Na2B4O7 + 3 H2O' },
    '47Q': { symbol: 'Na2B4O7', name: 'Bórax', reaction: '2 H3BO3 + 2 NaBO2 -> Na2B4O7 + 3 H2O' },
    '4Q7': { symbol: 'Na2B4O7', name: 'Bórax', reaction: '2 H3BO3 + 2 NaBO2 -> Na2B4O7 + 3 H2O' },
    'QY7': { symbol: 'NaSO4', name: 'Sulfato de sódio', reaction: 'H2SO4 + 2 NaOH -> Na2SO4 + 2 H2O' },
    'Q7Y': { symbol: 'NaSO4', name: 'Sulfato de sódio', reaction: 'H2SO4 + 2 NaOH -> Na2SO4 + 2 H2O' },
    'Y7Q': { symbol: 'NaSO4', name: 'Sulfato de sódio', reaction: 'H2SO4 + 2 NaOH -> Na2SO4 + 2 H2O' },
    'YQ7': { symbol: 'NaSO4', name: 'Sulfato de sódio', reaction: 'H2SO4 + 2 NaOH -> Na2SO4 + 2 H2O' },
    '7QY': { symbol: 'NaSO4', name: 'Sulfato de sódio', reaction: 'H2SO4 + 2 NaOH -> Na2SO4 + 2 H2O' },
    '7YQ': { symbol: 'NaSO4', name: 'Sulfato de sódio', reaction: 'H2SO4 + 2 NaOH -> Na2SO4 + 2 H2O' },
    'Q6': { symbol: 'NaN3', name: 'Trinitreto de sódio (azida de sódio)', reaction: '2 NaNH2 + N2O -> NaN3 + NaOH + NH3' },
    '6Q': { symbol: 'NaN3', name: 'Trinitreto de sódio (azida de sódio)', reaction: '2 NaNH2 + N2O -> NaN3 + NaOH + NH3' },
    '17W': { symbol: 'Mg(OH)2', name: 'Hidróxido de magnésio (leite de magnésia)', reaction: 'MgSO4 + 2 NaOH -> Mg(OH)2 + Na2SO4' },
    '1W7': { symbol: 'Mg(OH)2', name: 'Hidróxido de magnésio (leite de magnésia)', reaction: 'MgSO4 + 2 NaOH -> Mg(OH)2 + Na2SO4' },
    'W17': { symbol: 'Mg(OH)2', name: 'Hidróxido de magnésio (leite de magnésia)', reaction: 'MgSO4 + 2 NaOH -> Mg(OH)2 + Na2SO4' },
    'W71': { symbol: 'Mg(OH)2', name: 'Hidróxido de magnésio (leite de magnésia)', reaction: 'MgSO4 + 2 NaOH -> Mg(OH)2 + Na2SO4' },
    '7W1': { symbol: 'Mg(OH)2', name: 'Hidróxido de magnésio (leite de magnésia)', reaction: 'MgSO4 + 2 NaOH -> Mg(OH)2 + Na2SO4' },
    '71W': { symbol: 'Mg(OH)2', name: 'Hidróxido de magnésio (leite de magnésia)', reaction: 'MgSO4 + 2 NaOH -> Mg(OH)2 + Na2SO4' },
    'WU': { symbol: 'MgCl2', name: 'Cloreto de magnésio', reaction: 'Mg(OH)2 + 2 HCl -> MgCl2 + 2 H2O' },
    'UW': { symbol: 'MgCl2', name: 'Cloreto de magnésio', reaction: 'Mg(OH)2 + 2 HCl -> MgCl2 + 2 H2O' },
    'W7Y': { symbol: 'MgSO4', name: 'Sulfato de magnésio', reaction: 'Mg(OH)2 + H2SO4 -> 2 H2O + MgSO4' },
    'WY7': { symbol: 'MgSO4', name: 'Sulfato de magnésio', reaction: 'Mg(OH)2 + H2SO4 -> 2 H2O + MgSO4' },
    'YW7': { symbol: 'MgSO4', name: 'Sulfato de magnésio', reaction: 'Mg(OH)2 + H2SO4 -> 2 H2O + MgSO4' },
    'Y7W': { symbol: 'MgSO4', name: 'Sulfato de magnésio', reaction: 'Mg(OH)2 + H2SO4 -> 2 H2O + MgSO4' },
    '7YW': { symbol: 'MgSO4', name: 'Sulfato de magnésio', reaction: 'Mg(OH)2 + H2SO4 -> 2 H2O + MgSO4' },
    '7WY': { symbol: 'MgSO4', name: 'Sulfato de magnésio', reaction: 'Mg(OH)2 + H2SO4 -> 2 H2O + MgSO4' },
    'W75': { symbol: 'MgCO3', name: 'Carbonato de magnésio', reaction: 'Mg2 + (CO3)2 -> 2 MgCO3' },
    'W57': { symbol: 'MgCO3', name: 'Carbonato de magnésio', reaction: 'Mg2 + (CO3)2 -> 2 MgCO3' },
    '7W5': { symbol: 'MgCO3', name: 'Carbonato de magnésio', reaction: 'Mg2 + (CO3)2 -> 2 MgCO3' },
    '75W': { symbol: 'MgCO3', name: 'Carbonato de magnésio', reaction: 'Mg2 + (CO3)2 -> 2 MgCO3' },
    '57W': { symbol: 'MgCO3', name: 'Carbonato de magnésio', reaction: 'Mg2 + (CO3)2 -> 2 MgCO3' },
    '5W7': { symbol: 'MgCO3', name: 'Carbonato de magnésio', reaction: 'Mg2 + (CO3)2 -> 2 MgCO3' },
    'W8': { symbol: 'MgF2', name: 'Fluoreto de magnésio', reaction: '2 HF + MgO -> H2O + MgF2' },
    '8W': { symbol: 'MgF2', name: 'Fluoreto de magnésio', reaction: '2 HF + MgO -> H2O + MgF2' },
    'W6': { symbol: 'Mg3N2', name: 'Nitreto de magnésio', reaction: '3 Mg + N2 -> Mg3N2' },
    '6W': { symbol: 'Mg3N2', name: 'Nitreto de magnésio', reaction: '3 Mg + N2 -> Mg3N2' },
    'E7': { symbol: 'Al2O3', name: 'Óxido de alumínio (alumina)', reaction: '2 Al(OH)3 + calor -> Al2O3 + 3 H2O' },
    '7E': { symbol: 'Al2O3', name: 'Óxido de alumínio (alumina)', reaction: '2 Al(OH)3 + calor -> Al2O3 + 3 H2O' },
    'E71': { symbol: 'Al(OH)3', name: 'Hidróxido de alumínio', reaction: 'NaAl(OH)4 + resfriamento -> Al(OH)3 + NaOH' },
    'E17': { symbol: 'Al(OH)3', name: 'Hidróxido de alumínio', reaction: 'NaAl(OH)4 + resfriamento -> Al(OH)3 + NaOH' },
    '1E7': { symbol: 'Al(OH)3', name: 'Hidróxido de alumínio', reaction: 'NaAl(OH)4 + resfriamento -> Al(OH)3 + NaOH' },
    '17E': { symbol: 'Al(OH)3', name: 'Hidróxido de alumínio', reaction: 'NaAl(OH)4 + resfriamento -> Al(OH)3 + NaOH' },
    '7E1': { symbol: 'Al(OH)3', name: 'Hidróxido de alumínio', reaction: 'NaAl(OH)4 + resfriamento -> Al(OH)3 + NaOH' },
    '71E': { symbol: 'Al(OH)3', name: 'Hidróxido de alumínio', reaction: 'NaAl(OH)4 + resfriamento -> Al(OH)3 + NaOH' },
    'EU': { symbol: 'AlCl3', name: 'Cloreto de alumínio', reaction: '2 Al + 6 HCl -> AlCl3 + 3 H2' },
    'UE': { symbol: 'AlCl3', name: 'Cloreto de alumínio', reaction: '2 Al + 6 HCl -> AlCl3 + 3 H2' },
    'E7Y': { symbol: 'Al2(SO4)3', name: 'Sulfato de alumínio', reaction: '3 H2SO4 + 2 Al(OH)3 -> Al2(SO4)3 + 6 H2O' },
    'EY7': { symbol: 'Al2(SO4)3', name: 'Sulfato de alumínio', reaction: '3 H2SO4 + 2 Al(OH)3 -> Al2(SO4)3 + 6 H2O' },
    'YE7': { symbol: 'Al2(SO4)3', name: 'Sulfato de alumínio', reaction: '3 H2SO4 + 2 Al(OH)3 -> Al2(SO4)3 + 6 H2O' },
    'Y7E': { symbol: 'Al2(SO4)3', name: 'Sulfato de alumínio', reaction: '3 H2SO4 + 2 Al(OH)3 -> Al2(SO4)3 + 6 H2O' },
    '7EY': { symbol: 'Al2(SO4)3', name: 'Sulfato de alumínio', reaction: '3 H2SO4 + 2 Al(OH)3 -> Al2(SO4)3 + 6 H2O' },
    '7YE': { symbol: 'Al2(SO4)3', name: 'Sulfato de alumínio', reaction: '3 H2SO4 + 2 Al(OH)3 -> Al2(SO4)3 + 6 H2O' },
    'E5': { symbol: 'Al4C3', name: 'Carbeto de alumínio', reaction: '2 Al2O3 + 9 C -> Al4C3 + 6 CO' },
    '5E': { symbol: 'Al4C3', name: 'Carbeto de alumínio', reaction: '2 Al2O3 + 9 C -> Al4C3 + 6 CO' },
    'R7': { symbol: 'SiO2', name: 'Dióxido de silício (sílica)', reaction: 'SiH4 + 2 H2O -> SiO2 + 4 H2' },
    '7R': { symbol: 'SiO2', name: 'Dióxido de silício (sílica)', reaction: 'SiH4 + 2 H2O -> SiO2 + 4 H2' },
    'RU': { symbol: 'SiCl4', name: 'Tetracloreto de silício', reaction: 'Si + 2 Cl2 -> SiCl4' },
    'UR': { symbol: 'SiCl4', name: 'Tetracloreto de silício', reaction: 'Si + 2 Cl2 -> SiCl4' },
    'R1': { symbol: 'SiH4', name: 'Silano', reaction: 'Mg2Si + 4 HCl -> 2 MgCl2 + SiH4' },
    '1R': { symbol: 'SiH4', name: 'Silano', reaction: 'Mg2Si + 4 HCl -> 2 MgCl2 + SiH4' },
    '17R': { symbol: 'H2SiO3', name: 'Ácido metassílico', reaction: 'SiO2 + H2O -> H2SiO3' },
    '1R7': { symbol: 'H2SiO3', name: 'Ácido metassílico', reaction: 'SiO2 + H2O -> H2SiO3' },
    '71R': { symbol: 'H2SiO3', name: 'Ácido metassílico', reaction: 'SiO2 + H2O -> H2SiO3' },
    '7R1': { symbol: 'H2SiO3', name: 'Ácido metassílico', reaction: 'SiO2 + H2O -> H2SiO3' },
    'R17': { symbol: 'H2SiO3', name: 'Ácido metassílico', reaction: 'SiO2 + H2O -> H2SiO3' },
    'R71': { symbol: 'H2SiO3', name: 'Ácido metassílico', reaction: 'SiO2 + H2O -> H2SiO3' },
    'R5': { symbol: 'SiC', name: 'Carbeto de silício', reaction: 'SiO2 + 3 C -> SiC + 2CO' },
    '5R': { symbol: 'SiC', name: 'Carbeto de silício', reaction: 'SiO2 + 3 C -> SiC + 2CO' },
    'R6': { symbol: 'Si3N4', name: 'Nitreto de silício', reaction: '3 Si + 2 N2 -> Si3N4' },
    '6R': { symbol: 'Si3N4', name: 'Nitreto de silício', reaction: '3 Si + 2 N2 -> Si3N4' },
    'T7': { symbol: 'P4O6', name: 'Trióxido de fósforo', reaction: 'P4 + 3 O2 -> P4O6' },
    '7T': { symbol: 'P4O6', name: 'Trióxido de fósforo', reaction: 'P4 + 3 O2 -> P4O6' },
    'TU': { symbol: 'PCl3', name: 'Tricloreto de fósforo', reaction: 'P4 + 6 Cl2 -> 4 PCl3' },
    'UT': { symbol: 'PCl3', name: 'Tricloreto de fósforo', reaction: 'P4 + 6 Cl2 -> 4 PCl3' },
    'TU7': { symbol: 'POCl3', name: 'Cloreto de fosforila', reaction: '2 PCl3 + O2 -> 2 POCl3' },
    'T7U': { symbol: 'POCl3', name: 'Cloreto de fosforila', reaction: '2 PCl3 + O2 -> 2 POCl3' },
    'UT7': { symbol: 'POCl3', name: 'Cloreto de fosforila', reaction: '2 PCl3 + O2 -> 2 POCl3' },
    'U7T': { symbol: 'POCl3', name: 'Cloreto de fosforila', reaction: '2 PCl3 + O2 -> 2 POCl3' },
    '7UT': { symbol: 'POCl3', name: 'Cloreto de fosforila', reaction: '2 PCl3 + O2 -> 2 POCl3' },
    '7TU': { symbol: 'POCl3', name: 'Cloreto de fosforila', reaction: '2 PCl3 + O2 -> 2 POCl3' },
    'T1': { symbol: 'PH3', name: 'Hidreto de fósforo (fosfina)', reaction: '3 NaOH + 4 P + 3 H2O -> 3 NaH2PO2 + PH3' },
    '1T': { symbol: 'PH3', name: 'Hidreto de fósforo (fosfina)', reaction: '3 NaOH + 4 P + 3 H2O -> 3 NaH2PO2 + PH3' },
    'T17': { symbol: 'H3PO4', name: 'Ácido fosfórico', reaction: 'P2O5 + 3 H2O -> 2 H3PO4' },
    'T71': { symbol: 'H3PO4', name: 'Ácido fosfórico', reaction: 'P2O5 + 3 H2O -> 2 H3PO4' },
    '7T1': { symbol: 'H3PO4', name: 'Ácido fosfórico', reaction: 'P2O5 + 3 H2O -> 2 H3PO4' },
    '71T': { symbol: 'H3PO4', name: 'Ácido fosfórico', reaction: 'P2O5 + 3 H2O -> 2 H3PO4' },
    '17T': { symbol: 'H3PO4', name: 'Ácido fosfórico', reaction: 'P2O5 + 3 H2O -> 2 H3PO4' },
    '1T7': { symbol: 'H3PO4', name: 'Ácido fosfórico', reaction: 'P2O5 + 3 H2O -> 2 H3PO4' },
    'Y7': { symbol: 'SO2', name: 'Dióxido de enxofre', reaction: '2 H2S + 3 O2 -> 2 H2O + 2 SO2' },
    '7Y': { symbol: 'SO2', name: 'Dióxido de enxofre', reaction: '2 H2S + 3 O2 -> 2 H2O + 2 SO2' },
    '1Y': { symbol: 'H2S', name: 'Sulfeto de hidrogênio', reaction: '6 H2O + Al2S3 -> 3 H2S + 2 Al(OH)3' },
    'Y1': { symbol: 'H2S', name: 'Sulfeto de hidrogênio', reaction: '6 H2O + Al2S3 -> 3 H2S + 2 Al(OH)3' },
    'Y17': { symbol: 'H2SO4 e H2SO3', name: 'Ácido sulfúrico e ácido sulforoso', reaction: 'SO3 + H2O -> H2SO4 e SO2 + H2O -> H2SO3' },
    'Y71': { symbol: 'H2SO4 e H2SO3', name: 'Ácido sulfúrico e ácido sulforoso', reaction: 'SO3 + H2O -> H2SO4 e SO2 + H2O -> H2SO3' },
    '7Y1': { symbol: 'H2SO4 e H2SO3', name: 'Ácido sulfúrico e ácido sulforoso', reaction: 'SO3 + H2O -> H2SO4 e SO2 + H2O -> H2SO3' },
    '71Y': { symbol: 'H2SO4 e H2SO3', name: 'Ácido sulfúrico e ácido sulforoso', reaction: 'SO3 + H2O -> H2SO4 e SO2 + H2O -> H2SO3' },
    '17Y': { symbol: 'H2SO4 e H2SO3', name: 'Ácido sulfúrico e ácido sulforoso', reaction: 'SO3 + H2O -> H2SO4 e SO2 + H2O -> H2SO3' },
    '1Y7': { symbol: 'H2SO4 e H2SO3', name: 'Ácido sulfúrico e ácido sulforoso', reaction: 'SO3 + H2O -> H2SO4 e SO2 + H2O -> H2SO3' },
    'UA': { symbol: 'KCl', name: 'Cloreto de potássio', reaction: 'KOH + HCl -> KCl + H2O' },
    'AU': { symbol: 'KCl', name: 'Cloreto de potássio', reaction: 'KOH + HCl -> KCl + H2O' },
    'A7': { symbol: 'KO2', name: 'Superóxido de potássio', reaction: 'KOH + 3 O2 -> 4 KO2 + 2 H2O' },
    '7A': { symbol: 'KO2', name: 'Superóxido de potássio', reaction: 'KOH + 3 O2 -> 4 KO2 + 2 H2O' },
    'AY7': { symbol: 'K2SO4', name: 'Sulfato de potássio', reaction: 'H2SO4 + 2 KOH -> K2SO4 + 2 H2O' },
    'A7Y': { symbol: 'K2SO4', name: 'Sulfato de potássio', reaction: 'H2SO4 + 2 KOH -> K2SO4 + 2 H2O' },
    'YA7': { symbol: 'K2SO4', name: 'Sulfato de potássio', reaction: 'H2SO4 + 2 KOH -> K2SO4 + 2 H2O' },
    'Y7A': { symbol: 'K2SO4', name: 'Sulfato de potássio', reaction: 'H2SO4 + 2 KOH -> K2SO4 + 2 H2O' },
    '7AY': { symbol: 'K2SO4', name: 'Sulfato de potássio', reaction: 'H2SO4 + 2 KOH -> K2SO4 + 2 H2O' },
    '7YA': { symbol: 'K2SO4', name: 'Sulfato de potássio', reaction: 'H2SO4 + 2 KOH -> K2SO4 + 2 H2O' },
    'HA': { symbol: 'KI', name: 'Iodeto de potássio', reaction: '6 KOH + 3 I2 -> 5 KI + KIO3 + 3 H2O' },
    'AH': { symbol: 'KI', name: 'Iodeto de potássio', reaction: '6 KOH + 3 I2 -> 5 KI + KIO3 + 3 H2O' },
    'A17': { symbol: 'KOH', name: 'Hidróxido de potássio', reaction: 'K + H2O -> KOH + H2' },
    'A71': { symbol: 'KOH', name: 'Hidróxido de potássio', reaction: 'K + H2O -> KOH + H2' },
    '7A1': { symbol: 'KOH', name: 'Hidróxido de potássio', reaction: 'K + H2O -> KOH + H2' },
    '71A': { symbol: 'KOH', name: 'Hidróxido de potássio', reaction: 'K + H2O -> KOH + H2' },
    '17A': { symbol: 'KOH', name: 'Hidróxido de potássio', reaction: 'K + H2O -> KOH + H2' },
    '1A7': { symbol: 'KOH', name: 'Hidróxido de potássio', reaction: 'K + H2O -> KOH + H2' },
    'A7T': { symbol: 'K3PO4', name: 'Fosfato de potássio', reaction: 'H3PO4 + 3 KOH -> K3PO4 + 3 H2O' },
    'AT7': { symbol: 'K3PO4', name: 'Fosfato de potássio', reaction: 'H3PO4 + 3 KOH -> K3PO4 + 3 H2O' },
    'TA7': { symbol: 'K3PO4', name: 'Fosfato de potássio', reaction: 'H3PO4 + 3 KOH -> K3PO4 + 3 H2O' },
    'T7A': { symbol: 'K3PO4', name: 'Fosfato de potássio', reaction: 'H3PO4 + 3 KOH -> K3PO4 + 3 H2O' },
    '7TA': { symbol: 'K3PO4', name: 'Fosfato de potássio', reaction: 'H3PO4 + 3 KOH -> K3PO4 + 3 H2O' },
    '7AT': { symbol: 'K3PO4', name: 'Fosfato de potássio', reaction: 'H3PO4 + 3 KOH -> K3PO4 + 3 H2O' },
    'A57': { symbol: 'K2CO3', name: 'Carbonato de potássio', reaction: '2 KOH + CO2 -> K2CO3 + H2O' },
    'A75': { symbol: 'K2CO3', name: 'Carbonato de potássio', reaction: '2 KOH + CO2 -> K2CO3 + H2O' },
    '57A': { symbol: 'K2CO3', name: 'Carbonato de potássio', reaction: '2 KOH + CO2 -> K2CO3 + H2O' },
    '5A7': { symbol: 'K2CO3', name: 'Carbonato de potássio', reaction: '2 KOH + CO2 -> K2CO3 + H2O' },
    '7A5': { symbol: 'K2CO3', name: 'Carbonato de potássio', reaction: '2 KOH + CO2 -> K2CO3 + H2O' },
    '75A': { symbol: 'K2CO3', name: 'Carbonato de potássio', reaction: '2 KOH + CO2 -> K2CO3 + H2O' },
    'SY7': { symbol: 'CaSO4', name: 'Sulfato de cálcio (gesso)', reaction: 'CaCl2 + Na2SO4 -> CaSO4 + 2 NaCl' },
    'S7Y': { symbol: 'CaSO4', name: 'Sulfato de cálcio (gesso)', reaction: 'CaCl2 + Na2SO4 -> CaSO4 + 2 NaCl' },
    'YS7': { symbol: 'CaSO4', name: 'Sulfato de cálcio (gesso)', reaction: 'CaCl2 + Na2SO4 -> CaSO4 + 2 NaCl' },
    'Y7S': { symbol: 'CaSO4', name: 'Sulfato de cálcio (gesso)', reaction: 'CaCl2 + Na2SO4 -> CaSO4 + 2 NaCl' },
    '7YS': { symbol: 'CaSO4', name: 'Sulfato de cálcio (gesso)', reaction: 'CaCl2 + Na2SO4 -> CaSO4 + 2 NaCl' },
    '7SY': { symbol: 'CaSO4', name: 'Sulfato de cálcio (gesso)', reaction: 'CaCl2 + Na2SO4 -> CaSO4 + 2 NaCl' },
    'S57': { symbol: 'CaCO3', name: 'Carbonato de cálcio (calcário)', reaction: 'Ca(OH)2 + CO2 -> CaCO3 + H2O' },
    'S75': { symbol: 'CaCO3', name: 'Carbonato de cálcio (calcário)', reaction: 'Ca(OH)2 + CO2 -> CaCO3 + H2O' },
    '7S5': { symbol: 'CaCO3', name: 'Carbonato de cálcio (calcário)', reaction: 'Ca(OH)2 + CO2 -> CaCO3 + H2O' },
    '75S': { symbol: 'CaCO3', name: 'Carbonato de cálcio (calcário)', reaction: 'Ca(OH)2 + CO2 -> CaCO3 + H2O' },
    '5S7': { symbol: 'CaCO3', name: 'Carbonato de cálcio (calcário)', reaction: 'Ca(OH)2 + CO2 -> CaCO3 + H2O' },
    '57S': { symbol: 'CaCO3', name: 'Carbonato de cálcio (calcário)', reaction: 'Ca(OH)2 + CO2 -> CaCO3 + H2O' },
    'S7': { symbol: 'CaO', name: 'Óxido de cálcio (cal)', reaction: 'CaCO3 -> CaO + CO2' },
    '7S': { symbol: 'CaO', name: 'Óxido de cálcio (cal)', reaction: 'CaCO3 -> CaO + CO2' },
    '7SR': { symbol: 'CaSiO3', name: 'Metassilicato de cálcio', reaction: 'CaO + SiO2 -> CaSiO3' },
    '7RS': { symbol: 'CaSiO3', name: 'Metassilicato de cálcio', reaction: 'CaO + SiO2 -> CaSiO3' },
    'R7S': { symbol: 'CaSiO3', name: 'Metassilicato de cálcio', reaction: 'CaO + SiO2 -> CaSiO3' },
    'RS7': { symbol: 'CaSiO3', name: 'Metassilicato de cálcio', reaction: 'CaO + SiO2 -> CaSiO3' },
    'SR7': { symbol: 'CaSiO3', name: 'Metassilicato de cálcio', reaction: 'CaO + SiO2 -> CaSiO3' },
    'S7R': { symbol: 'CaSiO3', name: 'Metassilicato de cálcio', reaction: 'CaO + SiO2 -> CaSiO3' },
    'S7T': { symbol: 'Ca3(PO4)2', name: 'Fosfato de cálcio', reaction: '3 CaCO3 + 2 H3PO4 -> Ca3(PO4)2 + 3 CO2 + 3 H2O' },
    'ST7': { symbol: 'Ca3(PO4)2', name: 'Fosfato de cálcio', reaction: '3 CaCO3 + 2 H3PO4 -> Ca3(PO4)2 + 3 CO2 + 3 H2O' },
    'TS7': { symbol: 'Ca3(PO4)2', name: 'Fosfato de cálcio', reaction: '3 CaCO3 + 2 H3PO4 -> Ca3(PO4)2 + 3 CO2 + 3 H2O' },
    'T7S': { symbol: 'Ca3(PO4)2', name: 'Fosfato de cálcio', reaction: '3 CaCO3 + 2 H3PO4 -> Ca3(PO4)2 + 3 CO2 + 3 H2O' },
    '7TS': { symbol: 'Ca3(PO4)2', name: 'Fosfato de cálcio', reaction: '3 CaCO3 + 2 H3PO4 -> Ca3(PO4)2 + 3 CO2 + 3 H2O' },
    '7ST': { symbol: 'Ca3(PO4)2', name: 'Fosfato de cálcio', reaction: '3 CaCO3 + 2 H3PO4 -> Ca3(PO4)2 + 3 CO2 + 3 H2O' },
    '07': { symbol: 'TiO2', name: 'Dióxido de titânio (rutilo)', reaction: 'TiCl4 + 2 H2O -> TiO2 + 4 HCl' },
    '70': { symbol: 'TiO2', name: 'Dióxido de titânio (rutilo)', reaction: 'TiCl4 + 2 H2O -> TiO2 + 4 HCl' },
    '70O': { symbol: 'FeTiO3', name: 'Titanato de ferro (ilmenita)', reaction: '2 FeCl3 + 2 TiO2 + 2 H2O -> 2 FeTiO3 + 4 HCl + Cl2' },
    '7O0': { symbol: 'FeTiO3', name: 'Titanato de ferro (ilmenita)', reaction: '2 FeCl3 + 2 TiO2 + 2 H2O -> 2 FeTiO3 + 4 HCl + Cl2' },
    '07O': { symbol: 'FeTiO3', name: 'Titanato de ferro (ilmenita)', reaction: '2 FeCl3 + 2 TiO2 + 2 H2O -> 2 FeTiO3 + 4 HCl + Cl2' },
    '0O7': { symbol: 'FeTiO3', name: 'Titanato de ferro (ilmenita)', reaction: '2 FeCl3 + 2 TiO2 + 2 H2O -> 2 FeTiO3 + 4 HCl + Cl2' },
    'O70': { symbol: 'FeTiO3', name: 'Titanato de ferro (ilmenita)', reaction: '2 FeCl3 + 2 TiO2 + 2 H2O -> 2 FeTiO3 + 4 HCl + Cl2' },
    'O07': { symbol: 'FeTiO3', name: 'Titanato de ferro (ilmenita)', reaction: '2 FeCl3 + 2 TiO2 + 2 H2O -> 2 FeTiO3 + 4 HCl + Cl2' },
    '0U': { symbol: 'TiCl4', name: 'Tetracloreto de titânio', reaction: 'Ti + 2Cl2 -> TiCl4' },
    'U0': { symbol: 'TiCl4', name: 'Tetracloreto de titânio', reaction: 'Ti + 2Cl2 -> TiCl4' },
    '06': { symbol: 'TiN', name: 'Nitreto de titânio', reaction: 'TiCl4 + NH3 -> TiN + 4 HCl' },
    '60': { symbol: 'TiN', name: 'Nitreto de titânio', reaction: 'TiCl4 + NH3 -> TiN + 4 HCl' },
    '-7': { symbol: 'Cr2O3', name: 'Óxido de cromo', reaction: 'Cr2(SO4)3 + 3 H2O -> Cr2O3 + 3 H2SO4' },
    '7-': { symbol: 'Cr2O3', name: 'Óxido de cromo', reaction: 'Cr2(SO4)3 + 3 H2O -> Cr2O3 + 3 H2SO4' },
    '-71': { symbol: 'H2CrO4', name: 'Ácido crômico', reaction: 'Na2CrO4 + 2 H2O -> 2 NaOH + H2CrO4' },
    '-17': { symbol: 'H2CrO4', name: 'Ácido crômico', reaction: 'Na2CrO4 + 2 H2O -> 2 NaOH + H2CrO4' },
    '7-1': { symbol: 'H2CrO4', name: 'Ácido crômico', reaction: 'Na2CrO4 + 2 H2O -> 2 NaOH + H2CrO4' },
    '71-': { symbol: 'H2CrO4', name: 'Ácido crômico', reaction: 'Na2CrO4 + 2 H2O -> 2 NaOH + H2CrO4' },
    '17-': { symbol: 'H2CrO4', name: 'Ácido crômico', reaction: 'Na2CrO4 + 2 H2O -> 2 NaOH + H2CrO4' },
    '1-7': { symbol: 'H2CrO4', name: 'Ácido crômico', reaction: 'Na2CrO4 + 2 H2O -> 2 NaOH + H2CrO4' },
    '-O7': { symbol: 'FeCr2O4', name: 'Cromito de ferro (cromita)', reaction: '8 K2CrO4 + 2 Fe2O3 + 8 CO2 -> 4 FeCr2O4 + 8 K2CO3 + 7 O2' },
    '-7O': { symbol: 'FeCr2O4', name: 'Cromito de ferro (cromita)', reaction: '8 K2CrO4 + 2 Fe2O3 + 8 CO2 -> 4 FeCr2O4 + 8 K2CO3 + 7 O2' },
    '7-O': { symbol: 'FeCr2O4', name: 'Cromito de ferro (cromita)', reaction: '8 K2CrO4 + 2 Fe2O3 + 8 CO2 -> 4 FeCr2O4 + 8 K2CO3 + 7 O2' },
    '7O-': { symbol: 'FeCr2O4', name: 'Cromito de ferro (cromita)', reaction: '8 K2CrO4 + 2 Fe2O3 + 8 CO2 -> 4 FeCr2O4 + 8 K2CO3 + 7 O2' },
    'O7-': { symbol: 'FeCr2O4', name: 'Cromito de ferro (cromita)', reaction: '8 K2CrO4 + 2 Fe2O3 + 8 CO2 -> 4 FeCr2O4 + 8 K2CO3 + 7 O2' },
    'O-7': { symbol: 'FeCr2O4', name: 'Cromito de ferro (cromita)', reaction: '8 K2CrO4 + 2 Fe2O3 + 8 CO2 -> 4 FeCr2O4 + 8 K2CO3 + 7 O2' },
    '-Q7': { symbol: 'Na2CrO4', name: 'Cromato de sódio', reaction: '2 FeCr2O4 + 8 NaOH + 3/2 O2 -> 4 Na2CrO4 + Fe2O3 + 4 H2O' },
    '-7Q': { symbol: 'Na2CrO4', name: 'Cromato de sódio', reaction: '2 FeCr2O4 + 8 NaOH + 3/2 O2 -> 4 Na2CrO4 + Fe2O3 + 4 H2O' },
    '7-Q': { symbol: 'Na2CrO4', name: 'Cromato de sódio', reaction: '2 FeCr2O4 + 8 NaOH + 3/2 O2 -> 4 Na2CrO4 + Fe2O3 + 4 H2O' },
    '7Q-': { symbol: 'Na2CrO4', name: 'Cromato de sódio', reaction: '2 FeCr2O4 + 8 NaOH + 3/2 O2 -> 4 Na2CrO4 + Fe2O3 + 4 H2O' },
    'Q-7': { symbol: 'Na2CrO4', name: 'Cromato de sódio', reaction: '2 FeCr2O4 + 8 NaOH + 3/2 O2 -> 4 Na2CrO4 + Fe2O3 + 4 H2O' },
    'Q7-': { symbol: 'Na2CrO4', name: 'Cromato de sódio', reaction: '2 FeCr2O4 + 8 NaOH + 3/2 O2 -> 4 Na2CrO4 + Fe2O3 + 4 H2O' },
    '-7H': { symbol: 'CrI3', name: 'Iodeto de cromo', reaction: 'CrCl3 + I2 -> CrI3 + Cl2' },
    '-H7': { symbol: 'CrI3', name: 'Iodeto de cromo', reaction: 'CrCl3 + I2 -> CrI3 + Cl2' },
    '7-H': { symbol: 'CrI3', name: 'Iodeto de cromo', reaction: 'CrCl3 + I2 -> CrI3 + Cl2' },
    '7H-': { symbol: 'CrI3', name: 'Iodeto de cromo', reaction: 'CrCl3 + I2 -> CrI3 + Cl2' },
    'H-7': { symbol: 'CrI3', name: 'Iodeto de cromo', reaction: 'CrCl3 + I2 -> CrI3 + Cl2' },
    'H7-': { symbol: 'CrI3', name: 'Iodeto de cromo', reaction: 'CrCl3 + I2 -> CrI3 + Cl2' },
    '=7': { symbol: 'MnO2', name: 'Dióxido de manganês', reaction: 'Mn + O2 -> MnO2' },
    '7=': { symbol: 'MnO2', name: 'Dióxido de manganês', reaction: 'Mn + O2 -> MnO2' },
    '=7Y': { symbol: 'MnSO4', name: 'Sulfato de manganês', reaction: 'MnO2 + SO2 -> MnSO4' },
    '=Y7': { symbol: 'MnSO4', name: 'Sulfato de manganês', reaction: 'MnO2 + SO2 -> MnSO4' },
    'Y=7': { symbol: 'MnSO4', name: 'Sulfato de manganês', reaction: 'MnO2 + SO2 -> MnSO4' },
    'Y7=': { symbol: 'MnSO4', name: 'Sulfato de manganês', reaction: 'MnO2 + SO2 -> MnSO4' },
    '7=Y': { symbol: 'MnSO4', name: 'Sulfato de manganês', reaction: 'MnO2 + SO2 -> MnSO4' },
    '7Y=': { symbol: 'MnSO4', name: 'Sulfato de manganês', reaction: 'MnO2 + SO2 -> MnSO4' },
    'OY': { symbol: 'FeS2', name: 'Pirita', reaction: 'Fe3S4 + SO2 -> 3 FeS2' },
    'YO': { symbol: 'FeS2', name: 'Pirita', reaction: 'Fe3S4 + SO2 -> 3 FeS2' },
    'O7': { symbol: 'Fe2O3', name: 'Hematita', reaction: '4 FeS2 + 11 O2 -> 2 Fe2O3 + 8 SO2' },
    '7O': { symbol: 'Fe2O3', name: 'Hematita', reaction: '4 FeS2 + 11 O2 -> 2 Fe2O3 + 8 SO2' },
    'OY7': { symbol: 'FeSO4', name: 'Sulfato de ferro', reaction: 'Fe2O3 + SO3 + SO2 -> 2 FeSO4' },
    'O7Y': { symbol: 'FeSO4', name: 'Sulfato de ferro', reaction: 'Fe2O3 + SO3 + SO2 -> 2 FeSO4' },
    'YO7': { symbol: 'FeSO4', name: 'Sulfato de ferro', reaction: 'Fe2O3 + SO3 + SO2 -> 2 FeSO4' },
    'Y7O': { symbol: 'FeSO4', name: 'Sulfato de ferro', reaction: 'Fe2O3 + SO3 + SO2 -> 2 FeSO4' },
    '7YO': { symbol: 'FeSO4', name: 'Sulfato de ferro', reaction: 'Fe2O3 + SO3 + SO2 -> 2 FeSO4' },
    '7OY': { symbol: 'FeSO4', name: 'Sulfato de ferro', reaction: 'Fe2O3 + SO3 + SO2 -> 2 FeSO4' },
    'O17': { symbol: 'Fe(OH)3', name: 'Hidróxido de ferro', reaction: 'Fe(NO3)3 + 3 NaOH -> Fe(OH)3 + 3 NaNO3' },
    'O71': { symbol: 'Fe(OH)3', name: 'Hidróxido de ferro', reaction: 'Fe(NO3)3 + 3 NaOH -> Fe(OH)3 + 3 NaNO3' },
    '71O': { symbol: 'Fe(OH)3', name: 'Hidróxido de ferro', reaction: 'Fe(NO3)3 + 3 NaOH -> Fe(OH)3 + 3 NaNO3' },
    '7O1': { symbol: 'Fe(OH)3', name: 'Hidróxido de ferro', reaction: 'Fe(NO3)3 + 3 NaOH -> Fe(OH)3 + 3 NaNO3' },
    '17O': { symbol: 'Fe(OH)3', name: 'Hidróxido de ferro', reaction: 'Fe(NO3)3 + 3 NaOH -> Fe(OH)3 + 3 NaNO3' },
    '1O7': { symbol: 'Fe(OH)3', name: 'Hidróxido de ferro', reaction: 'Fe(NO3)3 + 3 NaOH -> Fe(OH)3 + 3 NaNO3' },
    'O75': { symbol: 'Fe(CO)5', name: 'Pentacarbonila de ferro', reaction: '5 Fe(CO)4I2 + 10Cu -> 10 CuI + 4 Fe(CO)5 + Fe' },
    'O57': { symbol: 'Fe(CO)5', name: 'Pentacarbonila de ferro', reaction: '5 Fe(CO)4I2 + 10Cu -> 10 CuI + 4 Fe(CO)5 + Fe' },
    '7O5': { symbol: 'Fe(CO)5', name: 'Pentacarbonila de ferro', reaction: '5 Fe(CO)4I2 + 10Cu -> 10 CuI + 4 Fe(CO)5 + Fe' },
    '75O': { symbol: 'Fe(CO)5', name: 'Pentacarbonila de ferro', reaction: '5 Fe(CO)4I2 + 10Cu -> 10 CuI + 4 Fe(CO)5 + Fe' },
    '5O7': { symbol: 'Fe(CO)5', name: 'Pentacarbonila de ferro', reaction: '5 Fe(CO)4I2 + 10Cu -> 10 CuI + 4 Fe(CO)5 + Fe' },
    '57O': { symbol: 'Fe(CO)5', name: 'Pentacarbonila de ferro', reaction: '5 Fe(CO)4I2 + 10Cu -> 10 CuI + 4 Fe(CO)5 + Fe' },
    'P7': { symbol: 'CoO', name: 'Óxido de cobalto', reaction: '2 Co3O4 -> 6 CoO + O2' },
    '7P': { symbol: 'CoO', name: 'Óxido de cobalto', reaction: '2 Co3O4 -> 6 CoO + O2' },
    '´7': { symbol: 'NiO', name: 'Óxido de níquel', reaction: '4 NiCrO -> 2 Cr2O3 + 4 NiO + 3 O2' },
    '7´': { symbol: 'NiO', name: 'Óxido de níquel', reaction: '4 NiCrO -> 2 Cr2O3 + 4 NiO + 3 O2' },
    '´75': { symbol: 'Ni(CO)4', name: 'Tetracarbonila de níquel', reaction: '4 CO + Ni -> Ni(CO)4' },
    '´57': { symbol: 'Ni(CO)4', name: 'Tetracarbonila de níquel', reaction: '4 CO + Ni -> Ni(CO)4' },
    '5´7': { symbol: 'Ni(CO)4', name: 'Tetracarbonila de níquel', reaction: '4 CO + Ni -> Ni(CO)4' },
    '57´': { symbol: 'Ni(CO)4', name: 'Tetracarbonila de níquel', reaction: '4 CO + Ni -> Ni(CO)4' },
    '7´5': { symbol: 'Ni(CO)4', name: 'Tetracarbonila de níquel', reaction: '4 CO + Ni -> Ni(CO)4' },
    '75´': { symbol: 'Ni(CO)4', name: 'Tetracarbonila de níquel', reaction: '4 CO + Ni -> Ni(CO)4' },
    '[Y7': { symbol: 'CuSO4', name: 'Sulfato de cobre', reaction: 'Cu(OH)2 + Na2SO4 -> 2 NaOH + CuSO4' },
    '[7Y': { symbol: 'CuSO4', name: 'Sulfato de cobre', reaction: 'Cu(OH)2 + Na2SO4 -> 2 NaOH + CuSO4' },
    '7[Y': { symbol: 'CuSO4', name: 'Sulfato de cobre', reaction: 'Cu(OH)2 + Na2SO4 -> 2 NaOH + CuSO4' },
    '7Y[': { symbol: 'CuSO4', name: 'Sulfato de cobre', reaction: 'Cu(OH)2 + Na2SO4 -> 2 NaOH + CuSO4' },
    'Y[7': { symbol: 'CuSO4', name: 'Sulfato de cobre', reaction: 'Cu(OH)2 + Na2SO4 -> 2 NaOH + CuSO4' },
    'Y7[': { symbol: 'CuSO4', name: 'Sulfato de cobre', reaction: 'Cu(OH)2 + Na2SO4 -> 2 NaOH + CuSO4' },
    '[OY': { symbol: 'CuFeS2', name: 'Calcopirita', reaction: '2 CuS + 2 FeO + 2 SO2 -> 2 CuFeS2 + 3 O2' },
    '[YO': { symbol: 'CuFeS2', name: 'Calcopirita', reaction: '2 CuS + 2 FeO + 2 SO2 -> 2 CuFeS2 + 3 O2' },
    'Y[O': { symbol: 'CuFeS2', name: 'Calcopirita', reaction: '2 CuS + 2 FeO + 2 SO2 -> 2 CuFeS2 + 3 O2' },
    'YO[': { symbol: 'CuFeS2', name: 'Calcopirita', reaction: '2 CuS + 2 FeO + 2 SO2 -> 2 CuFeS2 + 3 O2' },
    'OY[': { symbol: 'CuFeS2', name: 'Calcopirita', reaction: '2 CuS + 2 FeO + 2 SO2 -> 2 CuFeS2 + 3 O2' },
    'O[Y': { symbol: 'CuFeS2', name: 'Calcopirita', reaction: '2 CuS + 2 FeO + 2 SO2 -> 2 CuFeS2 + 3 O2' },
    'ÇY7': { symbol: 'ZnSO4', name: 'Sulfato de zinco', reaction: 'Zn + H2SO4 -> ZNSO4 + H2' },
    'YÇ7': { symbol: 'ZnSO4', name: 'Sulfato de zinco', reaction: 'Zn + H2SO4 -> ZNSO4 + H2' },
    'Ç7Y': { symbol: 'ZnSO4', name: 'Sulfato de zinco', reaction: 'Zn + H2SO4 -> ZNSO4 + H2' },
    'Y7Ç': { symbol: 'ZnSO4', name: 'Sulfato de zinco', reaction: 'Zn + H2SO4 -> ZNSO4 + H2' },
    '7ÇY': { symbol: 'ZnSO4', name: 'Sulfato de zinco', reaction: 'Zn + H2SO4 -> ZNSO4 + H2' },
    '7YÇ': { symbol: 'ZnSO4', name: 'Sulfato de zinco', reaction: 'Zn + H2SO4 -> ZNSO4 + H2' },
    'D6': { symbol: 'GaN', name: 'Nitreto de gálio', reaction: '2 Ga + 2 NH3 -> 2 GaN + 3 H2' },
    '6D': { symbol: 'GaN', name: 'Nitreto de gálio', reaction: '2 Ga + 2 NH3 -> 2 GaN + 3 H2' },
    'DU': { symbol: 'GaCl3', name: 'Cloreto de gálio', reaction: '2 Ga + 3 Cl2 -> 2 GaCl3' },
    'UD': { symbol: 'GaCl3', name: 'Cloreto de gálio', reaction: '2 Ga + 3 Cl2 -> 2 GaCl3' },
    'DG': { symbol: 'GaBr3', name: 'Brometo de gálio', reaction: '2 Ga + 3 Br2 -> 2 GaBr3' },
    'GD': { symbol: 'GaBr3', name: 'Brometo de gálio', reaction: '2 Ga + 3 Br2 -> 2 GaBr3' },
    '1G': { symbol: 'HBr', name: 'Ácido bromídrico', reaction: 'NaBr + HCl -> HBr + NaCl' },
    'G1': { symbol: 'HBr', name: 'Ácido bromídrico', reaction: 'NaBr + HCl -> HBr + NaCl'},
    '1U': { symbol: 'HCl', name: 'Ácido clorídrico', reaction: 'NaCl + H2O -> HCl + NaOH' },
    'U1': { symbol: 'HCl', name: 'Ácido clorídrico', reaction: 'NaCl + H2O -> HCl + NaOH' },
    'Z75': { symbol: 'SrCO3', name: 'Carboneto de estrôncio', reaction: 'SrO + CO2 -> SrCO3' },
    'Z57': { symbol: 'SrCO3', name: 'Carboneto de estrôncio', reaction: 'SrO + CO2 -> SrCO3' },
    '7Z5': { symbol: 'SrCO3', name: 'Carboneto de estrôncio', reaction: 'SrO + CO2 -> SrCO3' },
    '75Z': { symbol: 'SrCO3', name: 'Carboneto de estrôncio', reaction: 'SrO + CO2 -> SrCO3' },
    '57Z': { symbol: 'SrCO3', name: 'Carboneto de estrôncio', reaction: 'SrO + CO2 -> SrCO3' },
    '5Z7': { symbol: 'SrCO3', name: 'Carboneto de estrôncio', reaction: 'SrO + CO2 -> SrCO3' },
    'ZH': { symbol: 'SrI2', name: 'Iodeto de estrôncio', reaction: 'Sr + I2 -> SrI2' },
    'HZ': { symbol: 'SrI2', name: 'Iodeto de estrôncio', reaction: 'Sr + I2 -> SrI2' },
    '~U': { symbol: 'PdCl2', name: 'Cloreto de paládio', reaction: 'Pd + Cl2 -> PdCl2' },
    'U~': { symbol: 'PdCl2', name: 'Cloreto de paládio', reaction: 'Pd + Cl2 -> PdCl2' },
    '~H': { symbol: 'PdI2', name: 'Iodeto de paládio', reaction: 'Pd + I2 -> PdI2' },
    'H~': { symbol: 'PdI2', name: 'Iodeto de paládio', reaction: 'Pd + I2 -> PdI2' },
    '~G': { symbol: 'PdBr2', name: 'Brometo de paládio', reaction: 'Pd + Br2 -> PdBr2' },
    'G~': { symbol: 'PdBr2', name: 'Brometo de paládio', reaction: 'Pd + Br2 -> PdBr2' },
    '~8': { symbol: 'PdF2', name: 'Fluoreto de paládio', reaction: 'Pd + F2 -> PdF2' },
    '8~': { symbol: 'PdF2', name: 'Fluoreto de paládio', reaction: 'Pd + F2 -> PdF2' },
    ']67': { symbol: 'AgNO3', name: 'Nitrato de prata', reaction: '4 Ag + O2 + 4 HNO3 -> 4 AgNO3 + 2 H2O' },
    ']76': { symbol: 'AgNO3', name: 'Nitrato de prata', reaction: '4 Ag + O2 + 4 HNO3 -> 4 AgNO3 + 2 H2O' },
    '7]6': { symbol: 'AgNO3', name: 'Nitrato de prata', reaction: '4 Ag + O2 + 4 HNO3 -> 4 AgNO3 + 2 H2O' },
    '76]': { symbol: 'AgNO3', name: 'Nitrato de prata', reaction: '4 Ag + O2 + 4 HNO3 -> 4 AgNO3 + 2 H2O' },
    '6]7': { symbol: 'AgNO3', name: 'Nitrato de prata', reaction: '4 Ag + O2 + 4 HNO3 -> 4 AgNO3 + 2 H2O' },
    '67]': { symbol: 'AgNO3', name: 'Nitrato de prata', reaction: '4 Ag + O2 + 4 HNO3 -> 4 AgNO3 + 2 H2O' },
    'V7': { symbol: 'SnO2', name: 'Dióxido de estanho (cassiterita)', reaction: 'SnO + 1/2 O2 -> SnO2' },
    '7V': { symbol: 'SnO2', name: 'Dióxido de estanho (cassiterita)', reaction: 'SnO + 1/2 O2 -> SnO2' },
    'H17': { symbol: 'HIO3', name: 'Ácido iódico', reaction: 'I2 + 5 Cl2 + 6 H2O -> 2 HIO3 + 10 HCl' },
    'H71': { symbol: 'HIO3', name: 'Ácido iódico', reaction: 'I2 + 5 Cl2 + 6 H2O -> 2 HIO3 + 10 HCl' },
    '7H1': { symbol: 'HIO3', name: 'Ácido iódico', reaction: 'I2 + 5 Cl2 + 6 H2O -> 2 HIO3 + 10 HCl' },
    '71H': { symbol: 'HIO3', name: 'Ácido iódico', reaction: 'I2 + 5 Cl2 + 6 H2O -> 2 HIO3 + 10 HCl' },
    '17H': { symbol: 'HIO3', name: 'Ácido iódico', reaction: 'I2 + 5 Cl2 + 6 H2O -> 2 HIO3 + 10 HCl' },
    '1H7': { symbol: 'HIO3', name: 'Ácido iódico', reaction: 'I2 + 5 Cl2 + 6 H2O -> 2 HIO3 + 10 HCl' },
    'H2': { symbol: 'LiI', name: 'Iodeto de lítio', reaction: 'LiH + I2 -> LiI + HI' },
    '2H': { symbol: 'LiI', name: 'Iodeto de lítio', reaction: 'LiH + I2 -> LiI + HI' },
    'H]': { symbol: 'AgI', name: 'Iodeto de prata', reaction: 'AgNO3 + KI -> AgI + KNO3' },
    ']H': { symbol: 'AgI', name: 'Iodeto de prata', reaction: 'AgNO3 + KI -> AgI + KNO3' },
    'K7': { symbol: 'XeO3', name: 'Trióxido de xenônio', reaction: '2 Xe + 3 O2 -> 2 XeO3' },
    '7K': { symbol: 'XeO3', name: 'Trióxido de xenônio', reaction: '2 Xe + 3 O2 -> 2 XeO3' },
    'K8': { symbol: 'XeF4', name: 'Tetrafluoreto de xenônio', reaction: 'Xe + O2 + 4 HF -> XeF4 + 2 H2O' },
    '8K': { symbol: 'XeF4', name: 'Tetrafluoreto de xenônio', reaction: 'Xe + O2 + 4 HF -> XeF4 + 2 H2O' },
    '17X': { symbol: 'CsOH', name: 'Hidróxido de césio', reaction: '2 Cs + 2 H2O -> 2 CsOH + H2' },
    '1X7': { symbol: 'CsOH', name: 'Hidróxido de césio', reaction: '2 Cs + 2 H2O -> 2 CsOH + H2' },
    '71X': { symbol: 'CsOH', name: 'Hidróxido de césio', reaction: '2 Cs + 2 H2O -> 2 CsOH + H2' },
    '7X1': { symbol: 'CsOH', name: 'Hidróxido de césio', reaction: '2 Cs + 2 H2O -> 2 CsOH + H2' },
    'X17': { symbol: 'CsOH', name: 'Hidróxido de césio', reaction: '2 Cs + 2 H2O -> 2 CsOH + H2' },
    'X71': { symbol: 'CsOH', name: 'Hidróxido de césio', reaction: '2 Cs + 2 H2O -> 2 CsOH + H2' },
    'XY7': { symbol: 'CsSO4', name: 'Sulfato de césio', reaction: '2 Cs + H2SO4 -> Cs2SO4 + H2' },
    'X7Y': { symbol: 'CsSO4', name: 'Sulfato de césio', reaction: '2 Cs + H2SO4 -> Cs2SO4 + H2' },
    'YX7': { symbol: 'CsSO4', name: 'Sulfato de césio', reaction: '2 Cs + H2SO4 -> Cs2SO4 + H2' },
    'Y7X': { symbol: 'CsSO4', name: 'Sulfato de césio', reaction: '2 Cs + H2SO4 -> Cs2SO4 + H2' },
    '7YX': { symbol: 'CsSO4', name: 'Sulfato de césio', reaction: '2 Cs + H2SO4 -> Cs2SO4 + H2' },
    '7XY': { symbol: 'CsSO4', name: 'Sulfato de césio', reaction: '2 Cs + H2SO4 -> Cs2SO4 + H2' },
    'XU': { symbol: 'CsCl', name: 'Cloreto de césio', reaction: '2 Cs + Cl2 -> 2 CsCl' },
    'UX': { symbol: 'CsCl', name: 'Cloreto de césio', reaction: '2 Cs + Cl2 -> 2 CsCl' },
    'XH': { symbol: 'CsI', name: 'Iodeto de césio', reaction: '2 Cs + I2 -> 2 CsI' },
    'HX': { symbol: 'CsI', name: 'Iodeto de césio', reaction: '2 Cs + I2 -> 2 CsI' },
    'XG': { symbol: 'CsBr', name: 'Brometo de césio', reaction: '2 Cs + Br2 -> 2 CsBr' },
    'GX': { symbol: 'CsBr', name: 'Brometo de césio', reaction: '2 Cs + Br2 -> 2 CsBr' },
    'X7': { symbol: 'CsO2', name: 'Superóxido de césio', reaction: '2 H2O + Cs -> CsO2 + 2 H2' },
    '7X': { symbol: 'CsO2', name: 'Superóxido de césio', reaction: '2 H2O + Cs -> CsO2 + 2 H2' },
    'C7': { symbol: 'BaO', name: 'Óxido de bário', reaction: 'Ba + 1/2 O2 -> BaO' },
    '7C': { symbol: 'BaO', name: 'Óxido de bário', reaction: 'Ba + 1/2 O2 -> BaO' },
    'C71': { symbol: 'Ba(OH)2', name: 'Hidróxido de bário', reaction: 'BaO + H2O -> Ba(OH)2' },
    'C17': { symbol: 'Ba(OH)2', name: 'Hidróxido de bário', reaction: 'BaO + H2O -> Ba(OH)2' },
    '71C': { symbol: 'Ba(OH)2', name: 'Hidróxido de bário', reaction: 'BaO + H2O -> Ba(OH)2' },
    '7C1': { symbol: 'Ba(OH)2', name: 'Hidróxido de bário', reaction: 'BaO + H2O -> Ba(OH)2' },
    '1C7': { symbol: 'Ba(OH)2', name: 'Hidróxido de bário', reaction: 'BaO + H2O -> Ba(OH)2' },
    '17C': { symbol: 'Ba(OH)2', name: 'Hidróxido de bário', reaction: 'BaO + H2O -> Ba(OH)2' },
    'C75': { symbol: 'BaCO3', name: 'Carbonato de bário', reaction: 'BaO + CO2 -> BaCO3' },
    'C57': { symbol: 'BaCO3', name: 'Carbonato de bário', reaction: 'BaO + CO2 -> BaCO3' },
    '75C': { symbol: 'BaCO3', name: 'Carbonato de bário', reaction: 'BaO + CO2 -> BaCO3' },
    '7C5': { symbol: 'BaCO3', name: 'Carbonato de bário', reaction: 'BaO + CO2 -> BaCO3' },
    '57C': { symbol: 'BaCO3', name: 'Carbonato de bário', reaction: 'BaO + CO2 -> BaCO3' },
    '5C7': { symbol: 'BaCO3', name: 'Carbonato de bário', reaction: 'BaO + CO2 -> BaCO3' },
    'C7Y': { symbol: 'BaSO4', name: 'Sulfato de bário', reaction: 'H2SO4 + BaO -> BaSO4 + H2O' },
    'CY7': { symbol: 'BaSO4', name: 'Sulfato de bário', reaction: 'H2SO4 + BaO -> BaSO4 + H2O' },
    'YC7': { symbol: 'BaSO4', name: 'Sulfato de bário', reaction: 'H2SO4 + BaO -> BaSO4 + H2O' },
    'Y7C': { symbol: 'BaSO4', name: 'Sulfato de bário', reaction: 'H2SO4 + BaO -> BaSO4 + H2O' },
    '7CY': { symbol: 'BaSO4', name: 'Sulfato de bário', reaction: 'H2SO4 + BaO -> BaSO4 + H2O' },
    '7YC': { symbol: 'BaSO4', name: 'Sulfato de bário', reaction: 'H2SO4 + BaO -> BaSO4 + H2O' },
    'CU': { symbol: 'BaCl2', name: 'Cloreto de bário', reaction: '2 HCl + Ba(OH)2 -> BaCl2 + 2 H2O' },
    'UC': { symbol: 'BaCl2', name: 'Cloreto de bário', reaction: '2 HCl + Ba(OH)2 -> BaCl2 + 2 H2O' },
    'CG': { symbol: 'BaBr2', name: 'Brometo de bário', reaction: '2 HBr + Ba(OH)2 -> BaBr2 + 2 H2O' },
    'GC': { symbol: 'BaBr2', name: 'Brometo de bário', reaction: '2 HBr + Ba(OH)2 -> BaBr2 + 2 H2O' },
    'L7': { symbol: 'WO2', name: 'Dióxido de tungstênio', reaction: '2 WO3 + W -> 3 WO2' },
    '7L': { symbol: 'WO2', name: 'Dióxido de tungstênio', reaction: '2 WO3 + W -> 3 WO2' },
    '.K8': { symbol: 'XePtF6', name: 'Hexafluoro-platinato de xenônio', reaction: 'Xe + PtF6 -> XePtF6' },
    '.8K': { symbol: 'XePtF6', name: 'Hexafluoro-platinato de xenônio', reaction: 'Xe + PtF6 -> XePtF6' },
    'K.8': { symbol: 'XePtF6', name: 'Hexafluoro-platinato de xenônio', reaction: 'Xe + PtF6 -> XePtF6' },
    'K8.': { symbol: 'XePtF6', name: 'Hexafluoro-platinato de xenônio', reaction: 'Xe + PtF6 -> XePtF6' },
    '8.K': { symbol: 'XePtF6', name: 'Hexafluoro-platinato de xenônio', reaction: 'Xe + PtF6 -> XePtF6' },
    '8K.': { symbol: 'XePtF6', name: 'Hexafluoro-platinato de xenônio', reaction: 'Xe + PtF6 -> XePtF6' },
    '.8': { symbol: 'PtF6', name: 'Hexafluoreto de platina', reaction: 'Pt + 3 F2 -> PtF6' },
    '8.': { symbol: 'PtF6', name: 'Hexafluoreto de platina', reaction: 'Pt + 3 F2 -> PtF6' },
    '.U': { symbol: 'PtCl4', name: 'Cloreto de platina', reaction: 'Pt + 2 Cl2 -> PtCl4' },
    'U.': { symbol: 'PtCl4', name: 'Cloreto de platina', reaction: 'Pt + 2 Cl2 -> PtCl4' },
    '.G': { symbol: 'PtBr4', name: 'Brometo de platina', reaction: 'Pt + 2 Br2 -> PtBr4' },
    'G.': { symbol: 'PtBr4', name: 'Brometo de platina', reaction: 'Pt + 2 Br2 -> PtBr4' },
    '.7': { symbol: 'PtO2', name: 'Dióxido de platina', reaction: 'Pt + O2 -> PtO2' },
    '7.': { symbol: 'PtO2', name: 'Dióxido de platina', reaction: 'Pt + O2 -> PtO2' },
    ';U': { symbol: 'AuCl3', name: 'Cloreto de ouro', reaction: '2 Au + 3 Cl2 -> 2 AuCl3' },
    'U;': { symbol: 'AuCl3', name: 'Cloreto de ouro', reaction: '2 Au + 3 Br2 -> 2 AuBr3' },
    ';G': { symbol: 'AuBr3', name: 'Brometo de ouro', reaction: '2 Au + 3 Br2 -> 2 AuBr3' },
    'G;': { symbol: 'AuBr3', name: 'Brometo de ouro', reaction: '2 Au + 3 Br2 -> 2 AuBr3' },
    ';1U': { symbol: 'HAuCl4', name: 'Ácido cloroáurico', reaction: '2 Au + 2 NOCl + 3 Cl2 + 2 HNO3 -> 2 HAuCl4 + 4 NO2' },
    ';U1': { symbol: 'HAuCl4', name: 'Ácido cloroáurico', reaction: '2 Au + 2 NOCl + 3 Cl2 + 2 HNO3 -> 2 HAuCl4 + 4 NO2' },
    '1;U': { symbol: 'HAuCl4', name: 'Ácido cloroáurico', reaction: '2 Au + 2 NOCl + 3 Cl2 + 2 HNO3 -> 2 HAuCl4 + 4 NO2' },
    '1U;': { symbol: 'HAuCl4', name: 'Ácido cloroáurico', reaction: '2 Au + 2 NOCl + 3 Cl2 + 2 HNO3 -> 2 HAuCl4 + 4 NO2' },
    'U;1': { symbol: 'HAuCl4', name: 'Ácido cloroáurico', reaction: '2 Au + 2 NOCl + 3 Cl2 + 2 HNO3 -> 2 HAuCl4 + 4 NO2' },
    'U1;': { symbol: 'HAuCl4', name: 'Ácido cloroáurico', reaction: '2 Au + 2 NOCl + 3 Cl2 + 2 HNO3 -> 2 HAuCl4 + 4 NO2' },
    'BU': { symbol: 'PbCl2', name: 'Cloreto de chumbo', reaction: '2 HCl + Pb(NO3)2 -> PbCl2 + 2 HNO3' },
    'UB': { symbol: 'PbCl2', name: 'Cloreto de chumbo', reaction: '2 HCl + Pb(NO3)2 -> PbCl2 + 2 HNO3' },
    'BG': { symbol: 'PbBr2', name: 'Brometo de chumbo', reaction: '2 HBr + Pb(NO3)2 -> PbBr2 + 2 HNO3' },
    'GB': { symbol: 'PbBr2', name: 'Brometo de chumbo', reaction: '2 HBr + Pb(NO3)2 -> PbBr2 + 2 HNO3' },
    'BH': { symbol: 'PbI2', name: 'Iodeto de chumbo', reaction: 'Pb(NO3)2 + 2 KI -> PbI2 + 2 KNO3' },
    'HB': { symbol: 'PbI2', name: 'Iodeto de chumbo', reaction: 'Pb(NO3)2 + 2 KI -> PbI2 + 2 KNO3' },
    'BY': { symbol: 'PbS', name: 'Sulfeto de chumbo (galena)', reaction: 'PbSO4 -> 2 O2 + PbS' },
    'YB': { symbol: 'PbS', name: 'Sulfeto de chumbo (galena)', reaction: 'PbSO4 -> 2 O2 + PbS' },
    'BY7': { symbol: 'PbSO4', name: 'Sulfato de chumbo', reaction: 'PbO2 + 2 H2SO4 -> PbSO4 + 2 H2O' },
    'B7Y': { symbol: 'PbSO4', name: 'Sulfato de chumbo', reaction: 'PbO2 + 2 H2SO4 -> PbSO4 + 2 H2O' },
    'YB7': { symbol: 'PbSO4', name: 'Sulfato de chumbo', reaction: 'PbO2 + 2 H2SO4 -> PbSO4 + 2 H2O' },
    'Y7B': { symbol: 'PbSO4', name: 'Sulfato de chumbo', reaction: 'PbO2 + 2 H2SO4 -> PbSO4 + 2 H2O' },
    '7BY': { symbol: 'PbSO4', name: 'Sulfato de chumbo', reaction: 'PbO2 + 2 H2SO4 -> PbSO4 + 2 H2O' },
    '7YB': { symbol: 'PbSO4', name: 'Sulfato de chumbo', reaction: 'PbO2 + 2 H2SO4 -> PbSO4 + 2 H2O' },
    'B8': { symbol: 'PbF2', name: 'Fluoreto de chumbo', reaction: '2 HF + Pb(NO3)2 -> PbF2 + 2 HNO3' },
    '8B': { symbol: 'PbF2', name: 'Fluoreto de chumbo', reaction: '2 HF + Pb(NO3)2 -> PbF2 + 2 HNO3' },
    ',U': { symbol: 'RaCl2', name: 'Cloreto de rádio', reaction: 'Ra(OH)2 + 2 HCl -> RaCl2 + 2 H2O' },
    'U,': { symbol: 'RaCl2', name: 'Cloreto de rádio', reaction: 'Ra(OH)2 + 2 HCl -> RaCl2 + 2 H2O' },
    ',G': { symbol: 'RaBr2', name: 'Brometo de rádio', reaction: 'Ra(OH)2 + 2 HBr -> RaBr2 + 2 H2O' },
    ',G': { symbol: 'RaBr2', name: 'Brometo de rádio', reaction: 'Ra(OH)2 + 2 HBr -> RaBr2 + 2 H2O' },
    ',8': { symbol: 'RaF2', name: 'Fluoreto de rádio', reaction: 'Ra(OH)2 + 2 HF -> RaF2 + 2 H2O' },
    '8,': { symbol: 'RaF2', name: 'Fluoreto de rádio', reaction: 'Ra(OH)2 + 2 HF -> RaF2 + 2 H2O' },
    ',17': { symbol: 'Ra(OH)2', name: 'Hidróxido de rádio', reaction:'RaO + H2O -> Ra(OH)2' },
    ',71': { symbol: 'Ra(OH)2', name: 'Hidróxido de rádio', reaction:'RaO + H2O -> Ra(OH)2' },
    '1,7': { symbol: 'Ra(OH)2', name: 'Hidróxido de rádio', reaction: 'RaO + H2O -> Ra(OH)2' },
    '17,': { symbol: 'Ra(OH)2', name: 'Hidróxido de rádio', reaction: 'RaO + H2O -> Ra(OH)2' },
    '7,1': { symbol: 'Ra(OH)2', name: 'Hidróxido de rádio', reaction: 'RaO + H2O -> Ra(OH)2' },
    '71,': { symbol: 'Ra(OH)2', name: 'Hidróxido de rádio', reaction: 'RaO + H2O -> Ra(OH)2' },
    ',6': { symbol: 'Ra3N2', name: 'Nitreto de rádio', reaction: '3 Ra + N2 -> Ra3N2' },
    '6,': { symbol: 'Ra3N2', name: 'Nitreto de rádio', reaction: '3 Ra + N2 -> Ra3N2' },
    ',Y7': { symbol: 'RaSO4', name: 'Sulfato de rádio', reaction: 'Ra(OH)2 + H2SO4 -> 2 H2O + RaSO4' },
    ',7Y': { symbol: 'RaSO4', name: 'Sulfato de rádio', reaction: 'Ra(OH)2 + H2SO4 -> 2 H2O + RaSO4' },
    '7,Y': { symbol: 'RaSO4', name: 'Sulfato de rádio', reaction: 'Ra(OH)2 + H2SO4 -> 2 H2O + RaSO4' },
    '7Y,': { symbol: 'RaSO4', name: 'Sulfato de rádio', reaction: 'Ra(OH)2 + H2SO4 -> 2 H2O + RaSO4' },
    'Y,7': { symbol: 'RaSO4', name: 'Sulfato de rádio', reaction: 'Ra(OH)2 + H2SO4 -> 2 H2O + RaSO4' },
    'Y7,': { symbol: 'RaSO4', name: 'Sulfato de rádio', reaction: 'Ra(OH)2 + H2SO4 -> 2 H2O + RaSO4' },

};

 const handleKeyPress = (key) => {
    const keyUpper = key.toUpperCase();
    if (elements.hasOwnProperty(keyUpper)) {
      setElementInfo(elements[keyUpper]);
    } else if (combinations.hasOwnProperty(keyUpper)) {
      setElementInfo(combinations[keyUpper]);
    } else {
      setElementInfo(null);
    }


  };

  return (
    
    <View style={styles.container}>
      <TextInput
        style={styles.input}
        onChangeText={handleKeyPress}
        autoCapitalize="none"
        maxLength={3}
      />
      {elementInfo && (
        <ElementCard
          symbol={elementInfo.symbol}
          name={elementInfo.name}
          atomicNumber={elementInfo.atomicNumber}
          atomicMass={elementInfo.atomicMass}
          reaction={elementInfo.reaction}
        />
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    padding: 20,
    marginBottom: 20,
    fontSize: 20,
    textAlign: 'center',
    width: 200,
  },
});

export default App;

